### ISSUE TITLE
封装层次不明、功能混乱

### ISSUE THREAD

**Issue by Vincentzzg** [Yuzeyang/GCDAsyncSocketManager#1]
1、为什么要封装成两个类GCDAsyncSocketCommunicationManager和GCDAsyncSocketManager？然后让一个单例去持有另一个单例
2、还有GCDAsyncSocketDelegate这个代理，从CommunicationManager到GCDAsyncSocketManager最后传给GCDAsyncSocket，代理实现的地方是CommunicationManager，但是CommunicationManager有没有直接持有GCDAsyncSocket对象，我有点看蒙了
3、能解释一下这两个类分别承担的任务吗？

**Comment by Yuzeyang** [comment]
1&3.GCDAsyncSocketCommunicationManager是提供给业务方调用的业务请求类，GCDAsyncSocketManager则是做Socket相关操作的类，之前是全部放在GCDAsyncSocketManager这个类里面做，但是随着业务需求的增长，里面的代码会加的非常多，实在不利于维护，而且socket层变动的不大，而业务请求相关的操作变动的会比较大，所以这部分我单独抽取出来，等于是基于GCDAsyncSocketManager类再封装了一下，可以参考service的封装，单例持有单例这个，是因为考虑到业务方可能不使用GCDAsyncSocketCommunicationManager类，他直接就调用GCDAsyncSocketManager来用
2.这个就是普通的代理设置，只是直接将CommunicationManager与GCDAsyncSocketDelegate绑定在一起而已

**Comment by Vincentzzg** [comment]
我能明白你的意思，不过应该还可以优化的更好

**Comment by Yuzeyang** [comment]
这个是对的，优化还是得跟着实际的需要走，没有最优，只有更优嘛

**Comment by Vincentzzg** [comment]
楼主可以把这个issue关掉了，哈哈

**Comment by Vincentzzg** [comment]
还有个现实问题想跟楼主请教下，现在封装的是客户端发起请求，然后几下type缓存callback。
毕竟是长连接，如果是服务端推送过来的消息呢，怎么处理？

**Comment by Yuzeyang** [comment]
推送过来用delegate去处理

**Comment by Vincentzzg** [comment]
我现在是在做IM，刚好用到这一块，delegate怎么处理？

**Comment by Yuzeyang** [comment]
在GCDAsyncSocketCommunicationManager声明代理协议，比如：

``` objective-c
- (void)socketReadedData:(id)data forType:(NSInteger)type;
```

然后在GCDAsyncSocketDelegate的代理方法

``` objective-c
- (void)socket:(GCDAsyncSocket *)sock didReadData:(NSData *)data withTag:(long)tag {
      // 接收到推送消息，调用socketReadedData:forType:方法
}
```

**Comment by Vincentzzg** [comment]
恩，看到代理了。我想了一下觉得可能有问题，delegate并不会根据不同的业务进行处理，所有实现了代理的地方都会被调用，这样会导致不管收到什么样的消息，实现代理的地方全部都会被调用。
这个是有问题的吧

**Comment by Yuzeyang** [comment]
如果是好几个类都设置代理的话，只有最后设置的那个类才会被调用
