### ISSUE TITLE
关于host地址配置问题

### ISSUE THREAD

**Issue by Args** [Yuzeyang/GCDAsyncSocketManager#2]
找了好久发现竟然写在了config里，建议在readme里提示下。另外，这样写的话如果想用你的框架建立不同地址的链接是否就有些麻烦了，建议还是放在manager里

**Comment by Yuzeyang** [comment]
@Args 恩，后面在对接的业务方数量增加之后的，发现原先这样配置实际上比较麻烦，没有考虑好，后来我新增了一个接口是让业务方自己配置环境参数，这样可操作性就比较大了，我更新下代码
